OverAllTest/find/find/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('shop', include('searchshop.urls')),
    path('admin/', admin.site.urls),
]

OverAllTest/find/searchshop/urls.py
from django.urls import path, include
from . import views
app_name = 'shop'   # 重点是这一行
urlpatterns = [
    path('', views.index, name='index'),
    path('search', views.search, name='search'),
    #  path(r'search/$', views.search, name='search')
    
]

OverAllTest/find/searchshop/models.py
from django.db import models

# Create your models here.
class Shopp(models.Model):
    shop_name = models.TextField(max_length=200)
    shop_price = models.IntegerField(default=0)
    shop_dsc = models.CharField(max_length=200)

OverAllTest/find/searchshop/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
from .models import Shopp
from haystack.forms import  ModelSearchForm
from haystack.query import EmptySearchQuerySet
def index(request):
    shop_list = Shopp.objects.all()
    context = {
        'query': '',
        'shop_list': shop_list
    }
    return render(request, 'searchshop/index.html', context)

def search(request,  load_all=True, form_class=ModelSearchForm, searchqueryset=None):
    if request.GET.get('q'):
        form = form_class(request.GET, searchqueryset=searchqueryset, load_all=load_all)

        if form.is_valid():
            query = form.cleaned_data['q']
            results = form.search()
            context = {
                'query': query,
                'shop_list': results
            }
            return render(request, 'searchshop/index.html', context)
            # results = form.search()
        return HttpResponse(request.GET.get('q'))
    return HttpResponse('查询')

OverAllTest/find/searchshop/templates/searchshop/index.html
{% load highlight %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>商品列表</title>
    <style>
        span.highlighted {
            color: red;
        }
    </style>
</head>

<body>
    <div class="search">
        <form method="get" action="{% url 'shop:search' %}">
            <input type="text" name="q" placeholder="a搜索商品">
            <input type="submit" value="搜索">
        </form>
    </div>




    {% if shop_list and query %}
    <ul>
        {% for question in shop_list %}
        <li>
            {% highlight question.object.shop_name with query %}
            价格： {% highlight question.object.shop_price with query %}
            <span class="post-author"> <a> {% highlight question.object.shop_dsc with query %} </a></span>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No polls are available.</p>
    {% endif %}

</body>

</html>